if IsDuplicityVersion() then

else
    RegisterCommand("testEverything", function(source, args, rawCommand)
        local pdata = ps.getPlayerData()
        local id = ps.getIdentifier()
        local metadata = ps.getMetadata("hunger")
        local charinfo = ps.getCharInfo("firstname")
        local playerName = ps.getPlayerName()
        local player = ps.getPlayer()
        local vehicleLabel = ps.getVehicleLabel(GetVehiclePedIsIn(player, false))
        local dead = ps.isDead()
        local job = ps.getJob()
        local jobName = ps.getJobName()
        local jobType = ps.getJobType()
        local jobDuty = ps.getJobDuty()
        local jobGrade = ps.getJobData('grade')
        local isBoss = ps.isBoss()
        local gang = ps.getGang()
        local gangName = ps.getGangName()
        local gangBoss = ps.isLeader()
        local gangGrade = ps.getGangData('grade')
        local image = ps.getImage("lockpick")
        local label = ps.getLabel("lockpick")
        local hasItem = ps.hasItem("lockpick", 1)
        local nearestPed = ps.getNearestPed()
        local nearestVehicle = ps.getNearestVehicle()
        local nearestObject = ps.getNearestObject()
        local nearestObjectofType = ps.getNearestObjectOfType("prop_barrel_01a")

        local nearestPlayer = ps.getNearestPlayers()
        local getNearbyVehicles = ps.getNearbyVehicles(10.0)
        local getNearbyObjects = ps.getNearbyObjects(10.0)
        local ray = ps.raycast()
        ps.debug("Player Data: ", pdata)
        ps.debug("Identifier: ", id)
        ps.debug("Metadata (Hunger): ", metadata)
        ps.debug("Char Info (First Name): ", charinfo)
        ps.debug("Player Name: ", playerName)
        ps.debug("Player: ", player)
        ps.debug("Vehicle Label: ", vehicleLabel)
        ps.debug("Is Dead: ", dead)
        ps.debug("Job: ", job)
        ps.debug("Job Name: ", jobName)
        ps.debug("Job Type: ", jobType)
        ps.debug("Job Duty: ", jobDuty)
        ps.debug("Job Grade: ", jobGrade)
        ps.debug("Is Boss: ", isBoss)
        ps.debug("Gang: ", gang)
        ps.debug("Gang Name: ", gangName)
        ps.debug("Gang Boss: ", gangBoss)
        ps.debug("Gang Grade: ", gangGrade)
        ps.debug("Image: ", image)
        ps.debug("Label: ", label)
        ps.debug("Has Item (Lockpick): ", hasItem)
        ps.debug("Nearest Ped: ", nearestPed)
        ps.debug("Nearest Vehicle: ", nearestVehicle)
        ps.debug("Nearest Object: ", nearestObject)
        ps.debug("Nearest Object of Type (Barrel): ", nearestObjectofType)
        ps.debug("Nearest Player: ", nearestPlayer)
        ps.debug("Nearby Vehicles: ", getNearbyVehicles)
        ps.debug("Nearby Objects: ", getNearbyObjects)
        ps.debug("Raycast Result: ", ray)
        ps.debug("Cache: ", ps.cache)

    end, false)
end